version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-2"
    ECR_REPO: "991524241826.dkr.ecr.ap-south-2.amazonaws.com/cloudstudents/shancourse"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 991524241826.dkr.ecr.ap-south-2.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO:$IMAGE_TAG course-service   # ✅ FIXED PATH
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest

artifacts:
  files:
    - '**/*'